#!/bin/bash

function do_for_sigint() {
  echo stopping
  myDate="$(date)"

  # targetDir="$(pwd)"
  targetDir="$(pwd)/video/$myDate"
  echo $targetDir

  mkdir ./video/"$myDate"
  mv *.ogg ./video/"$myDate"

  pkill -P $$
 exit
}

myTotalCameras="$(ls /dev/video* | wc -l)"
echo $myTotalCameras
for ((i=0;i<$myTotalCameras;i++))
do
    ( ./play_video $i & )
done

while true
do
  trap 'do_for_sigint' INT
done
# wait
# echo blah
exit
