#!/bin/bash

v4l2-ctl --device=/dev/video$1 -c power_line_frequency=0
v4l2-ctl --device=/dev/video$1 -c focus_auto=0
v4l2-ctl --device=/dev/video$1 -c focus_absolute=0
v4l2-ctl --device=/dev/video$1 -c white_balance_temperature_auto=0
v4l2-ctl --device=/dev/video$1 -c white_balance_temperature=4500
v4l2-ctl --device=/dev/video$1 -c exposure_auto=0
v4l2-ctl --device=/dev/video$1 -c exposure_absolute=175
v4l2-ctl --device=/dev/video$1 -c zoom_absolute=500

echo Number: $1
  ffmpeg -vcodec h264 -f v4l2 -video_size 1920x1080 -i /dev/video$1 -vcodec copy -y output$1.mkv
exit
