#!/bin/bash

# ls /dev/video* > media_list
#
# read -a video_list <<<$(cat media_list)
#
#
# vlc v4l2:///dev/video$1 #--sout=file/ps:go.mpg
# ffmpeg -b 100K -an -f video4linux2 -s 320x240 -r 10 -i /dev/audio0 -i /dev/video0 -b 100K -f ogg - | mplayer - -idle -demuxer ogg
hwNum=$((1 + $1))
echo $hwNum
# (
  cvlc v4l2:///dev/video$1:width=640:height=480 :input-slave=alsa://hw:$hwNum,0 --run-time $2 --stop-time=$2 vlc://quit --sout="#transcode{vcodec=theo,vb=2000,fps=20,scale=1.0,acodec=vorb,ab=90,channels=1,samplerate=44100}:standard{access=file,mux=ogg,dst=output"$1".ogg}"
#   exit
# )
  # PID=$!
  # echo blah
  # echo $PID
  # kill -INT PID
exit
# vlc v4l2:///dev/video1 --sout-standard-path=test.avi
# mencoder tv:// -tv driver=v4l2:width=800:height=600:device=/dev/video$1:fps=30:outfmt=yuy2:forceaudio:alsa:adevice=hw.2,0 -ovc lavc -lavcopts vcodec=mpeg4:vbitrate=1800 -ffourcc xvid -oac mp3lame -lameopts cbr=128 -o output4.avi
# mencoder tv:// -tv driver=v4l2:width=800:height=600:device=/dev/video2:fps=30:outfmt=yuy2:forceaudio:alsa:adevice=hw.2,0 -ovc lavc -lavcopts vcodec=mpeg4:vbitrate=1800 -ffourcc xvid -oac mp3lame -lameopts cbr=128 -o output5.avi
